Repository Team-Wash/Wash-Android, pull requests merged in 2024-08, with the labels that each got.

#14 Feature/solve
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/wash/washandroid/model/ChatItemModels.kt
  app/src/main/java/com/wash/washandroid/model/ChatModels.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/chat/ChatAdapter.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/chat/ChatApi.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/chat/ChatApiService.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/chat/ChatFragment.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/chat/ChatViewModel.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/problem/PhotoAdapter.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/problem/PhotoSliderAdapter.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/problem/PhotoSliderFragment.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/problem/add/PhotoNewAdapter.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/problem/add/ProblemAddFragment.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/problem/add/ProblemAnswerFragment.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/problem/add/ProblemAnswerViewModel.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/problem/old/ProblemInfoCategoryAdapter.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/problem/old/ProblemInfoFragment.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/problem/old/ProblemInfoViewModel.kt
  app/src/main/java/com/wash/washandroid/utils/ChatItemDecoration.kt
  app/src/main/java/com/wash/washandroid/utils/ProblemInfoDecoration.kt
  app/src/main/res/drawable/a_song_of_ice_and_fire.jpg
  app/src/main/res/drawable/chat_message_input.xml
  app/src/main/res/drawable/chat_message_send.xml
  app/src/main/res/drawable/chat_message_unsend.xml
  app/src/main/res/drawable/open_ai.xml
  app/src/main/res/drawable/photo_add.xml
  app/src/main/res/drawable/photo_add_btn_background.xml
  app/src/main/res/drawable/photo_close_btn.xml
  app/src/main/res/drawable/photo_delete.xml
  app/src/main/res/drawable/photo_delete_background.xml
  app/src/main/res/drawable/problem_add_btn.xml
  app/src/main/res/drawable/problem_info_answer_background.xml
  app/src/main/res/drawable/problem_info_background.xml
  app/src/main/res/drawable/problem_info_category_background.xml
  app/src/main/res/layout/fragment_chat.xml
  app/src/main/res/layout/fragment_photo_slider.xml
  app/src/main/res/layout/fragment_problem_add.xml
  app/src/main/res/layout/fragment_problem_answer.xml
  app/src/main/res/layout/fragment_problem_category_chapter.xml
  app/src/main/res/layout/fragment_problem_info.xml
  app/src/main/res/layout/item_chat.xml
  app/src/main/res/layout/item_photo.xml
  app/src/main/res/layout/item_photo_add_btn.xml
  app/src/main/res/layout/item_photo_fullscreen.xml
  app/src/main/res/layout/item_problem_info_category.xml
  app/src/main/res/navigation/mobile_navigation.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feature, 🎨 design

#20 [chore] 홈화면 제거 버튼 커스텀 #19
  app/src/main/res/drawable/photo_home_delete_background.xml
  app/src/main/res/layout/fragment_home_detail_recye_img.xml
  app/src/main/res/layout/item_note.xml
Labels: 🎨 design

#33 Feature/note study function
  app/src/main/java/com/wash/washandroid/presentation/customview/CropOverlayView.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/note/DeleteRectangleBottomSheet.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/note/NoteCameraFragment.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/note/NoteOptionsBottomSheet.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/note/NoteSelectAreaFragment.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/problem/add/ProblemAddFragment.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/study/StudyAnswerFragment.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/study/StudyCompleteFragment.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/study/StudyFolder.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/study/StudyFolderAdapter.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/study/StudyFragment.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/study/StudyPhotoSliderFragment.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/study/StudyProblem.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/study/StudyProgressAdapter.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/study/StudySolveFragment.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/study/StudyViewModel.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/study/data/api/StudyApiService.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/study/data/api/StudyRetrofitInstance.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/study/data/model/StudyFolder.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/study/data/model/StudyProblem.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/study/data/model/request/AnswerRequest.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/study/data/model/response/StudyAnswerResponse.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/study/data/model/response/StudyFolderIdResponse.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/study/data/model/response/StudyFolderResponse.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/study/data/model/response/StudyProblemResponse.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/study/data/model/response/StudyProgressResponse.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/study/data/repository/StudyRepository.kt
  app/src/main/res/drawable/note_select_rotate_btn.xml
  app/src/main/res/drawable/study_correct.xml
  app/src/main/res/drawable/study_sm_correct.xml
  app/src/main/res/drawable/study_sm_incomplete.xml
  app/src/main/res/drawable/study_sm_incorrect.xml
  app/src/main/res/layout/bottom_sheet_delete_rectangle.xml
  app/src/main/res/layout/fragment_note_select_area.xml
  app/src/main/res/layout/fragment_study_answer.xml
  app/src/main/res/layout/fragment_study_solve.xml
  app/src/main/res/layout/note_bottom_sheet_options.xml
  app/src/main/res/layout/study_item_drawer.xml
  app/src/main/res/navigation/mobile_navigation.xml
Labels: ✨ feature

#35 Feature/#18 api
  app/src/main/java/com/wash/washandroid/model/CategoryAddModels.kt
  app/src/main/java/com/wash/washandroid/model/CategoryFolderModels.kt
  app/src/main/java/com/wash/washandroid/model/CategoryModels.kt
  app/src/main/java/com/wash/washandroid/model/ChatModels.kt
  app/src/main/java/com/wash/washandroid/model/ChatOCRModels.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/category/ProblemCategoryChapterFragment.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/category/ProblemCategoryFolderFragment.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/category/ProblemCategorySubfieldFragment.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/category/ProblemCategorySubjectFragment.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/category/adapter/CategoryChapterAdapter.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/category/adapter/CategoryFolderAdapter.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/category/adapter/CategorySubfieldAdapter.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/category/adapter/CategorySubjectAdapter.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/category/dialog/CategoryChapterDialog.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/category/dialog/CategoryChapterDialogViewModel.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/category/dialog/CategoryFolderDialog.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/category/dialog/CategoryFolderDialogViewModel.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/category/dialog/CategorySubfieldDialog.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/category/dialog/CategorySubfieldDialogViewModel.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/category/dialog/CategorySubjectDialog.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/category/dialog/CategorySubjectDialogViewModel.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/category/network/CategoryApiService.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/category/network/NetworkModule.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/category/viewmodel/CategoryChapterViewModel.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/category/viewmodel/CategoryChoiceViewModel.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/category/viewmodel/CategoryFolderViewModel.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/category/viewmodel/CategorySubfieldViewModel.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/category/viewmodel/CategorySubjectViewModel.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/chat/ChatApiService.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/chat/ChatViewModel.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/problem/add/ProblemAddFragment.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/problem/add/ProblemAnswerFragment.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/problem/add/ProblemAnswerViewModel.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/problem/network/ProblemApiService.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/problem/network/ProblemInfoModels.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/problem/old/ProblemInfoCategoryAdapter.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/problem/old/ProblemInfoFragment.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/problem/old/ProblemInfoViewModel.kt
  app/src/main/java/com/wash/washandroid/utils/CategoryItemDecoration.kt
  app/src/main/res/drawable/category_add_dialog_background.xml
  app/src/main/res/layout/dialog_category_chapter.xml
  app/src/main/res/layout/dialog_category_folder.xml
  app/src/main/res/layout/dialog_category_subfield.xml
  app/src/main/res/layout/dialog_category_subject.xml
  app/src/main/res/layout/fragment_problem_add.xml
  app/src/main/res/layout/fragment_problem_answer.xml
  app/src/main/res/layout/fragment_problem_category_chapter.xml
  app/src/main/res/layout/fragment_problem_category_folder.xml
  app/src/main/res/layout/fragment_problem_category_subfield.xml
  app/src/main/res/layout/fragment_problem_category_subject.xml
  app/src/main/res/layout/fragment_problem_info.xml
  app/src/main/res/layout/item_category_btn.xml
  app/src/main/res/navigation/mobile_navigation.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/themes.xml
Labels: ✨ feature

#38 [chore] 문제 사진 영역 인식 후 이미지 설정
  app/src/main/java/com/wash/washandroid/presentation/fragment/problem/add/ProblemAddFragment.kt
Labels: 🐛 fix

#46 Fix/#40 study api
  app/src/main/java/com/wash/washandroid/presentation/customview/CropOverlayView.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/mypage/MypageViewModel.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/study/StudyAnswerFragment.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/study/StudyCompleteFragment.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/study/StudyFragment.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/study/StudyProgressAdapter.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/study/StudySolveFragment.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/study/StudyViewModel.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/study/data/api/StudyApiService.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/study/data/api/StudyRetrofitInstance.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/study/data/repository/StudyRepository.kt
Labels: 🐛 fix, ✨ feature

#55 Feat/#47 study problem move
  app/src/main/java/com/wash/washandroid/presentation/fragment/study/StudyAnswerFragment.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/study/StudyFragment.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/study/StudySolveFragment.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/study/StudyViewModel.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/study/data/repository/StudyRepository.kt
  app/src/main/res/layout/fragment_social_login.xml
Labels: 🐛 fix

#61 [FIX] 폴더 ordervalue로 불러오도록 수정 #47
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/wash/washandroid/presentation/fragment/study/StudyFolderAdapter.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/study/StudyFragment.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/study/StudyViewModel.kt
Labels: 🐛 fix

#66 Fix/#60 study add func
  app/build.gradle.kts
  app/src/main/java/com/wash/washandroid/presentation/customview/CropOverlayViewExample.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/mypage/data/service/RetrofitClient.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/study/StudyFolderAdapter.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/study/StudyFragment.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/study/StudyPhotoSliderFragment.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/study/StudySolveFragment.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/study/StudyViewModel.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/study/SwipeGestureListener.kt
  app/src/main/java/com/wash/washandroid/presentation/fragment/study/data/api/StudyRetrofitInstance.kt
  app/src/main/res/layout/fragment_study.xml
  app/src/main/res/layout/fragment_study_answer.xml
  app/src/main/res/layout/fragment_study_full_screen_image.xml
  app/src/main/res/layout/fragment_study_solve.xml
  app/src/main/res/layout/study_item_drawer.xml
  build.gradle.kts
Labels: 🐛 fix
